[package]
name = "list-members"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3"
futures-core = "0.3"
thiserror = "2"
tracing = "0.1"
twilight-http = "0.17"
twilight-model = "0.17"
